### ISSUE TITLE
Make a module page - parent

### ISSUE THREAD

**Issue by webfactorybulgaria** [TypiCMS/Pages#6]
After some time trying to find out why the page nesting doesn't work for me in the admin area I found out that it is an intentional restriction that if a page is linked to a module it cannot become a parent. This makes sense of course, if it causes some frontend misbehavior :)
There is a workaround this however - you can make a normal page a parent and then link it to a module. Maybe this can be prevented by an observer? i.e. if linking to a module - move all children to root level....
What do you think?

**Comment by sdebacker** [comment]
You are right, but auto moving all children pages to root could be a big problem (url change etc.). I propose to disable the select field of parent page, and add an help-block like this: "A page that containing children cannot be linked to a module". If you submit a PR, I will pull it, otherwise, I will integrate it in the next release.

**Comment by sdebacker** [comment]
Fixed by b50e46c68909bd0be100e0093e672c9094a8b3aa
